djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
]

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

jokes/urls.py
from django.urls import path

from .views import JokeListView

from .views import JokeDetailView, JokeListView

from .views import (
    JokeCreateView,JokeDeleteView,
      JokeDetailView, JokeListView, JokeUpdateView
)

app_name = 'jokes'
urlpatterns = [
    path('joke/<slug>/update/', JokeUpdateView.as_view(), name='update'),
    path('joke/<slug>/', JokeDetailView.as_view(), name='detail'),
    path('joke/<slug>/delete/', JokeDeleteView.as_view(), name='delete'),
    path('joke/create/', JokeCreateView.as_view(), name='create'),
    path('', JokeListView.as_view(), name='list'),
]

pages/urls.py
from django.urls import path

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
]

jobs/models.py
from django.db import models

# Create your models here.

jokes/models.py
from django.db import models
from django.urls import reverse
from common.utils.text import unique_slug

class Joke(models.Model):
    question = models.TextField(max_length=200)
    answer = models.TextField(max_length=100, blank=True)
    slug = models.SlugField(
    max_length=50, unique=True, null=False, editable=False
    )
       
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse('jokes:detail', args=[self.slug])
    
    def save(self, *args, **kwargs):
       if not self.slug:
           value = str(self)
           self.slug = unique_slug(value, type(self))

       super().save(*args, **kwargs)
    
    def __str__(self):
        return self.question
    
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

jobs/forms.py
from datetime import datetime
from django import forms

class JobApplicationForm(forms.Form):
    EMPLOYMENT_TYPES = (
        (None, '--Please choose--'),
        ('ft', 'Full-Time'),
        ('pt', 'Part-time'),
        ('contract', 'Contract work')
    )

    DAYS = (
        (1, 'MON'),
        (2, 'TUES'),
        (3, 'WED'),
        (4, 'THU'),
        (5, 'FRI')
    )
    YEARS = range(datetime.now().year, datetime.now().year+2)

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    last_name = forms.CharField()
    email = forms.EmailField()
    website = forms.URLField(
        required=False,
        widget=forms.URLInput(
            attrs={'placeholder': 'https://www.example.com', 'size':'50'}
        )
    )
    employment_type = forms.ChoiceField(choices=EMPLOYMENT_TYPES)
    start_date = forms.DateField(
        help_text='The earliest date you can start working.',
        widget=forms.SelectDateWidget(
            years=YEARS,
        )
    )
    available_days = forms.TypedMultipleChoiceField(
        choices=DAYS,
        coerce=int,
        help_text='Select all days that you can work.',
        widget=forms.CheckboxSelectMultiple(
            attrs={'checked':True}
        )
    )
    desired_hourly_wage = forms.DecimalField(
      widget=forms.NumberInput(
          attrs={'min':'10:00', 'max':'100.00', 'step':'.25'}
      )
    )
    cover_letter = forms.CharField(
        widget=forms.Textarea(attrs={'cols': '75', 'rows': '5'})
    )
    confirmation = forms.BooleanField(
        label='I certify that the information I have provided is true.'
    )

jobs/views.py
import html
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from common.utils.email import send_email
from .forms import JobApplicationForm

class JobAppView(FormView):
    template_name = 'jobs/joke_writer.html'
    form_class = JobApplicationForm
    success_url = reverse_lazy('jobs:thanks')

    def form_valid(self, form):
        data = form.cleaned_data
        to = 'ckiedaisch09@gmail.com'
        subject = 'Application for Joke Writer'
        content = f'''<p>Hey HR Manager!</p>
            <p>Job application received:</p>
            <ol>'''
        for key, value in data.items():
            label = key.replace('_', ' ').title()
            entry = html.escape(str(value), quote=False)
            content += f'<li>{label}: {entry}</li>'
        
        content += '</ol>'

        send_email(to, subject, content)
        return super().form_valid(form)

class JobAppThanksView(TemplateView):
    template_name = 'jobs/thanks.html'

jokes/views.py
from django.shortcuts import render

from django.views.generic import ListView

from .models import Joke

from django.views.generic import DetailView, ListView

from django.views.generic import CreateView, DetailView, ListView, UpdateView

from django.urls import reverse_lazy

from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)

class JokeListView(ListView):
    model = Joke

class JokeDetailView(DetailView):
    model = Joke

class JokeCreateView(CreateView):
    model = Joke
    fields = ['question', 'answer']

class JokeUpdateView(UpdateView):
    model = Joke
    fields = ['question', 'answer']

class JokeDeleteView(DeleteView):
    model = Joke
    success_url = reverse_lazy('jokes:list')    

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutUsView(TemplateView):
    template_name = 'pages/about-us.html'

users/views.py
from django.shortcuts import render

# Create your views here.

djangojokes/templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}Jokes{% endblock %}
{% block main %}
  <h2>Jokes</h2>
  <ul class="list-group list-group-flush mb-3">
    {% for joke in joke_list %}
      <li class="list-group-item">{{ joke.question }}</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="https://kit.fontawesome.com/21b71716a6.js" crossorigin="anonymous"></script>
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
<title>{% block title %}{% endblock %} | Django Jokes</title>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
      <img src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'jokes:list' %}">Jokes</a>
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Jokes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Log in</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
             role="button" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            Me
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">My Account</a>
            <a class="dropdown-item" href="#">Django Jokes</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Log out</a>
          </div>
        </li>
      </ul>
      <form class="row my-2 my-lg-0 row">
        <input class="form-control me-sm-2 col" type="search"
        placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 me-4 col" type="submit">
          Search
        </button>
      </form>
    </div>
  </nav>
</header>
<main class="m-4 pb-5">
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-end m-1 me-2">Copyright &copy; 2022 Django Jokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %}">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </nav>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

templates/common/joke.html
<div class="card border-primary m-auto mb-3 text-center"
  style="max-width: 30rem">
  <div class="card-header">Random Joke</div>
  <div class="card-body">
    <h5 class="card-title">{{ joke.question }}</h5>
    <p class="card-text">{{ joke.answer }}</p>
  </div>
</div>

templates/jobs/joke_writer.html
{% extends "_base.html" %}

{% block title %}Job Application: Joke Writer{% endblock %}
{% block main %}
  <h2 class="text-center">Joke Writer Application</h2>
  <div class="card border-primary m-auto mb-3 p-3" style="max-width: 40rem">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success float-end">Apply</button>
      </form>
  </div>
{% endblock %}

templates/jobs/thanks.html
{% extends "_base.html" %}

{% block title %}Job Application Submitted{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 p-3 text-center"
    style="max-width: 50rem">
    <p>Thanks! We will get back to you soon!</p>
  </div>
{% endblock %}

templates/jokes/joke_confirm_delete.html
{% extends "_base.html" %}

{% block title %}Delete Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <p><strong>Are you sure you want to delete this joke?</strong></p>
      <p>{{ joke.question }}</p>
      <button class="btn btn-success form-control">Confirm</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_detail.html
{% extends "_base.html" %}

{% block title %}Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <div class="card-header">{{ joke.question }}</div>
    <div class="card-body text-primary">
      <h5 class="card-title">{{ joke.answer }}</h5>
    </div>
    <div class="card-footer">
      <small class="text-muted">
        Created on: {{ joke.created }}
        Last updated: {{ joke.updated }}
      </small>
    </div>
  </div>
{% endblock %}

templates/jokes/joke_form.html
{% extends "_base.html" %}

{% block title %}Add/Update Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 p-3"
    style="max-width: 30rem">
    <form method="post">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
          </table>
      <button class="btn btn-success float-end">Submit</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}Jokes{% endblock %}
{% block main %}
  <a class="btn btn-success btn-sm float-end" href="{% url 'jokes:create' %}">
    + New Joke
  </a>
  <h2>Jokes</h2>
  <ul class="list-group list-group-flush mb-3">
    {% for joke in joke_list %}
      <li class="list-group-item">
        <a href="{{ joke.get_absolute_url }}">{{ joke.question }}</a>
        <a href="{% url 'jokes:update' joke.slug %}"
          class="btn btn-info btn-sm float-end me-2">Update</a>
        <a href="{% url 'jokes:delete' joke.slug %}"
          class="btn btn-danger btn-sm float-end me-2">Delete</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
  <h2>About Us</h2>
  <p>We tell funny jokes.</p>
  <p><a href="{% url 'jobs:app' %}">Work for us.</a></p>
{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}
{% load common_tags %}

{% block title %}Home{% endblock %}
{% block main %}
  <h2>Welcome!</h2>
  <p>Ready to laugh?</p>
{% random_joke %}
{% endblock %}